// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package sqlc

import (
	"context"
)

const addConsumerAPI = `-- name: AddConsumerAPI :exec
INSERT INTO inventory.component_api_consumers (
    component_id,
    api_id
) VALUES (
    $1,
    $2
)
`

type AddConsumerAPIParams struct {
	ComponentID int64
	ApiID       int64
}

func (q *Queries) AddConsumerAPI(ctx context.Context, arg AddConsumerAPIParams) error {
	_, err := q.db.Exec(ctx, addConsumerAPI, arg.ComponentID, arg.ApiID)
	return err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO inventory.components (
    product_id,
    name,
    description,
    component_type,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, product_id, name, description, component_type, details
`

type CreateComponentParams struct {
	ProductID     int64
	Name          string
	Description   *string
	ComponentType InventoryComponentType
	Details       []byte
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (InventoryComponent, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.ComponentType,
		arg.Details,
	)
	var i InventoryComponent
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.ComponentType,
		&i.Details,
	)
	return i, err
}

const createProviderAPI = `-- name: CreateProviderAPI :one
INSERT INTO inventory.apis (
    provider_component_id,
    name,
    api_type,
    network_exposure
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, provider_component_id, name, api_type, network_exposure
`

type CreateProviderAPIParams struct {
	ProviderComponentID int64
	Name                string
	ApiType             string
	NetworkExposure     InventoryNetworkExposure
}

func (q *Queries) CreateProviderAPI(ctx context.Context, arg CreateProviderAPIParams) (InventoryApi, error) {
	row := q.db.QueryRow(ctx, createProviderAPI,
		arg.ProviderComponentID,
		arg.Name,
		arg.ApiType,
		arg.NetworkExposure,
	)
	var i InventoryApi
	err := row.Scan(
		&i.ID,
		&i.ProviderComponentID,
		&i.Name,
		&i.ApiType,
		&i.NetworkExposure,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :one
DELETE FROM inventory.components
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteComponent, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getAPIProviderComponentID = `-- name: GetAPIProviderComponentID :one
SELECT provider_component_id
FROM inventory.apis
WHERE id = $1
`

func (q *Queries) GetAPIProviderComponentID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getAPIProviderComponentID, id)
	var provider_component_id int64
	err := row.Scan(&provider_component_id)
	return provider_component_id, err
}

const getComponentByID = `-- name: GetComponentByID :many
SELECT
    component.id,
    component.product_id,
    component.name,
    component.description,
    component.component_type,
    component.details,
    COALESCE(api.id, 0::BIGINT) AS api_id,
    COALESCE(api.name, ''::TEXT) AS api_name,
    COALESCE(api.api_type, ''::TEXT) AS api_type,
    COALESCE(api.network_exposure, 'internal'::inventory.network_exposure) AS api_network_exposure,
    COALESCE(api.api_role, ''::TEXT) AS api_role
FROM inventory.components AS component
LEFT JOIN LATERAL (
    SELECT
        provider_api.id,
        provider_api.name,
        provider_api.api_type,
        provider_api.network_exposure,
        'provider'::TEXT AS api_role,
        0::SMALLINT AS role_order
    FROM inventory.apis AS provider_api
    WHERE provider_api.provider_component_id = component.id

    UNION ALL

    SELECT
        consumer_api.id,
        consumer_api.name,
        consumer_api.api_type,
        consumer_api.network_exposure,
        'consumer'::TEXT AS api_role,
        1::SMALLINT AS role_order
    FROM inventory.component_api_consumers AS consumer
    JOIN inventory.apis AS consumer_api ON consumer_api.id = consumer.api_id
    WHERE consumer.component_id = component.id
) AS api ON TRUE
WHERE component.id = $1
ORDER BY api.role_order, api.id
`

type GetComponentByIDRow struct {
	ID                 int64
	ProductID          int64
	Name               string
	Description        *string
	ComponentType      InventoryComponentType
	Details            []byte
	ApiID              int64
	ApiName            string
	ApiType            string
	ApiNetworkExposure InventoryNetworkExposure
	ApiRole            string
}

func (q *Queries) GetComponentByID(ctx context.Context, id int64) ([]GetComponentByIDRow, error) {
	rows, err := q.db.Query(ctx, getComponentByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetComponentByIDRow{}
	for rows.Next() {
		var i GetComponentByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.ComponentType,
			&i.Details,
			&i.ApiID,
			&i.ApiName,
			&i.ApiType,
			&i.ApiNetworkExposure,
			&i.ApiRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByProductID = `-- name: ListComponentsByProductID :many
WITH paged_components AS (
    SELECT
        id,
        product_id,
        name,
        description,
        component_type,
        details
    FROM inventory.components
    WHERE product_id = $1
    ORDER BY id
    LIMIT $3
    OFFSET $2
)
SELECT
    component.id,
    component.product_id,
    component.name,
    component.description,
    component.component_type,
    component.details,
    COALESCE(api.id, 0::BIGINT) AS api_id,
    COALESCE(api.name, ''::TEXT) AS api_name,
    COALESCE(api.api_type, ''::TEXT) AS api_type,
    COALESCE(api.network_exposure, 'internal'::inventory.network_exposure) AS api_network_exposure,
    COALESCE(api.api_role, ''::TEXT) AS api_role
FROM paged_components AS component
LEFT JOIN LATERAL (
    SELECT
        provider_api.id,
        provider_api.name,
        provider_api.api_type,
        provider_api.network_exposure,
        'provider'::TEXT AS api_role,
        0::SMALLINT AS role_order
    FROM inventory.apis AS provider_api
    WHERE provider_api.provider_component_id = component.id

    UNION ALL

    SELECT
        consumer_api.id,
        consumer_api.name,
        consumer_api.api_type,
        consumer_api.network_exposure,
        'consumer'::TEXT AS api_role,
        1::SMALLINT AS role_order
    FROM inventory.component_api_consumers AS consumer
    JOIN inventory.apis AS consumer_api ON consumer_api.id = consumer.api_id
    WHERE consumer.component_id = component.id
) AS api ON TRUE
ORDER BY component.id, api.role_order, api.id
`

type ListComponentsByProductIDParams struct {
	ProductID int64
	Offset    int32
	Limit     int32
}

type ListComponentsByProductIDRow struct {
	ID                 int64
	ProductID          int64
	Name               string
	Description        *string
	ComponentType      InventoryComponentType
	Details            []byte
	ApiID              int64
	ApiName            string
	ApiType            string
	ApiNetworkExposure InventoryNetworkExposure
	ApiRole            string
}

func (q *Queries) ListComponentsByProductID(ctx context.Context, arg ListComponentsByProductIDParams) ([]ListComponentsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listComponentsByProductID, arg.ProductID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentsByProductIDRow{}
	for rows.Next() {
		var i ListComponentsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.ComponentType,
			&i.Details,
			&i.ApiID,
			&i.ApiName,
			&i.ApiType,
			&i.ApiNetworkExposure,
			&i.ApiRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConsumerAPI = `-- name: RemoveConsumerAPI :one
DELETE FROM inventory.component_api_consumers
WHERE component_id = $1 AND api_id = $2
RETURNING component_id
`

type RemoveConsumerAPIParams struct {
	ComponentID int64
	ApiID       int64
}

func (q *Queries) RemoveConsumerAPI(ctx context.Context, arg RemoveConsumerAPIParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeConsumerAPI, arg.ComponentID, arg.ApiID)
	var component_id int64
	err := row.Scan(&component_id)
	return component_id, err
}
