// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
)

type InventoryComponentType string

const (
	InventoryComponentTypeBackendService   InventoryComponentType = "Backend Service"
	InventoryComponentTypeFrontendService  InventoryComponentType = "Frontend Service"
	InventoryComponentTypeInfrastructure   InventoryComponentType = "Infrastructure"
	InventoryComponentTypeBackgroundWorker InventoryComponentType = "Background Worker"
)

func (e *InventoryComponentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryComponentType(s)
	case string:
		*e = InventoryComponentType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryComponentType: %T", src)
	}
	return nil
}

type NullInventoryComponentType struct {
	InventoryComponentType InventoryComponentType
	Valid                  bool // Valid is true if InventoryComponentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryComponentType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryComponentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryComponentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryComponentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryComponentType), nil
}

func (e InventoryComponentType) Valid() bool {
	switch e {
	case InventoryComponentTypeBackendService,
		InventoryComponentTypeFrontendService,
		InventoryComponentTypeInfrastructure,
		InventoryComponentTypeBackgroundWorker:
		return true
	}
	return false
}

type InventoryNetworkExposure string

const (
	InventoryNetworkExposureInternal InventoryNetworkExposure = "internal"
	InventoryNetworkExposureInternet InventoryNetworkExposure = "internet"
)

func (e *InventoryNetworkExposure) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryNetworkExposure(s)
	case string:
		*e = InventoryNetworkExposure(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryNetworkExposure: %T", src)
	}
	return nil
}

type NullInventoryNetworkExposure struct {
	InventoryNetworkExposure InventoryNetworkExposure
	Valid                    bool // Valid is true if InventoryNetworkExposure is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryNetworkExposure) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryNetworkExposure, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryNetworkExposure.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryNetworkExposure) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryNetworkExposure), nil
}

func (e InventoryNetworkExposure) Valid() bool {
	switch e {
	case InventoryNetworkExposureInternal,
		InventoryNetworkExposureInternet:
		return true
	}
	return false
}

type InventoryProductCriticality string

const (
	InventoryProductCriticalityMISSIONCRITICAL     InventoryProductCriticality = "MISSION-CRITICAL"
	InventoryProductCriticalityBUSINESSCRITICAL    InventoryProductCriticality = "BUSINESS-CRITICAL"
	InventoryProductCriticalityBUSINESSOPERATIONAL InventoryProductCriticality = "BUSINESS-OPERATIONAL"
	InventoryProductCriticalityOFFICEPRODUCTIVITY  InventoryProductCriticality = "OFFICE-PRODUCTIVITY"
)

func (e *InventoryProductCriticality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryProductCriticality(s)
	case string:
		*e = InventoryProductCriticality(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryProductCriticality: %T", src)
	}
	return nil
}

type NullInventoryProductCriticality struct {
	InventoryProductCriticality InventoryProductCriticality
	Valid                       bool // Valid is true if InventoryProductCriticality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryProductCriticality) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryProductCriticality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryProductCriticality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryProductCriticality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryProductCriticality), nil
}

func (e InventoryProductCriticality) Valid() bool {
	switch e {
	case InventoryProductCriticalityMISSIONCRITICAL,
		InventoryProductCriticalityBUSINESSCRITICAL,
		InventoryProductCriticalityBUSINESSOPERATIONAL,
		InventoryProductCriticalityOFFICEPRODUCTIVITY:
		return true
	}
	return false
}

type InventoryApi struct {
	ID                  int64
	ProviderComponentID int64
	Name                string
	ApiType             string
	NetworkExposure     InventoryNetworkExposure
}

type InventoryComponent struct {
	ID            int64
	ProductID     int64
	Name          string
	Description   *string
	ComponentType InventoryComponentType
	Details       []byte
}

type InventoryComponentApiConsumer struct {
	ComponentID int64
	ApiID       int64
}

type InventoryProduct struct {
	ID           int64
	WorkspaceID  int64
	ProductCode  string
	OwningTeamID *int64
	Name         string
	Criticality  InventoryProductCriticality
	Description  *string
}

type InventoryWorkspace struct {
	ID   int64
	Name string
}
