// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddConsumerAPI(ctx context.Context, arg AddConsumerAPIParams) error
	CreateComponent(ctx context.Context, arg CreateComponentParams) (InventoryComponent, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (InventoryProduct, error)
	CreateProviderAPI(ctx context.Context, arg CreateProviderAPIParams) (InventoryApi, error)
	CreateWorkspace(ctx context.Context, name string) (InventoryWorkspace, error)
	DeleteComponent(ctx context.Context, id int64) (int64, error)
	DeleteProduct(ctx context.Context, id int64) (int64, error)
	DeleteWorkspace(ctx context.Context, id int64) (int64, error)
	GetAPIProviderComponentID(ctx context.Context, id int64) (int64, error)
	GetComponentByID(ctx context.Context, id int64) ([]GetComponentByIDRow, error)
	GetProductByID(ctx context.Context, id int64) (InventoryProduct, error)
	GetWorkspaceByID(ctx context.Context, id int64) (InventoryWorkspace, error)
	ListComponentsByProductID(ctx context.Context, arg ListComponentsByProductIDParams) ([]ListComponentsByProductIDRow, error)
	ListProductsByWorkspaceID(ctx context.Context, arg ListProductsByWorkspaceIDParams) ([]InventoryProduct, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]InventoryWorkspace, error)
	RemoveConsumerAPI(ctx context.Context, arg RemoveConsumerAPIParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
