// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO inventory.workspaces (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (InventoryWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i InventoryWorkspace
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :one
DELETE FROM inventory.workspaces
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteWorkspace, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name
FROM inventory.workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (InventoryWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i InventoryWorkspace
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name
FROM inventory.workspaces
ORDER BY id
LIMIT $2
OFFSET $1
`

type ListWorkspacesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]InventoryWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryWorkspace{}
	for rows.Next() {
		var i InventoryWorkspace
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
