// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apis.sql

package sqlc

import (
	"context"
)

const batchCreateAPIs = `-- name: BatchCreateAPIs :many
WITH input AS (
    SELECT names.name, api_types.api_type, network_exposures.network_exposure, names.ordinality
    FROM unnest($2::TEXT[]) WITH ORDINALITY AS names(name, ordinality)
    JOIN unnest($3::TEXT[]) WITH ORDINALITY AS api_types(api_type, ordinality)
        USING (ordinality)
    JOIN unnest($4::TEXT[]) WITH ORDINALITY AS network_exposures(network_exposure, ordinality)
        USING (ordinality)
)
INSERT INTO inventory.apis (component_id, name, api_type, network_exposure)
SELECT $1, name, api_type, network_exposure::inventory.network_exposure
FROM input
ORDER BY ordinality
RETURNING id, component_id, name, api_type, network_exposure
`

type BatchCreateAPIsParams struct {
	ComponentID      int64
	Names            []string
	ApiTypes         []string
	NetworkExposures []string
}

func (q *Queries) BatchCreateAPIs(ctx context.Context, arg BatchCreateAPIsParams) ([]InventoryApi, error) {
	rows, err := q.db.Query(ctx, batchCreateAPIs,
		arg.ComponentID,
		arg.Names,
		arg.ApiTypes,
		arg.NetworkExposures,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryApi{}
	for rows.Next() {
		var i InventoryApi
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.Name,
			&i.ApiType,
			&i.NetworkExposure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAPIsByComponentID = `-- name: CountAPIsByComponentID :one
SELECT count(*)
FROM inventory.apis
WHERE component_id = $1
`

func (q *Queries) CountAPIsByComponentID(ctx context.Context, componentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIsByComponentID, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPI = `-- name: CreateAPI :one
INSERT INTO inventory.apis (
    component_id,
    name,
    api_type,
    network_exposure
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, component_id, name, api_type, network_exposure
`

type CreateAPIParams struct {
	ComponentID     int64
	Name            string
	ApiType         string
	NetworkExposure InventoryNetworkExposure
}

func (q *Queries) CreateAPI(ctx context.Context, arg CreateAPIParams) (InventoryApi, error) {
	row := q.db.QueryRow(ctx, createAPI,
		arg.ComponentID,
		arg.Name,
		arg.ApiType,
		arg.NetworkExposure,
	)
	var i InventoryApi
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Name,
		&i.ApiType,
		&i.NetworkExposure,
	)
	return i, err
}

const listAPIsByComponentIDs = `-- name: ListAPIsByComponentIDs :many
SELECT component_id, id, name, api_type, network_exposure
FROM inventory.apis
WHERE component_id = ANY($1::BIGINT[])
ORDER BY component_id, id
`

type ListAPIsByComponentIDsRow struct {
	ComponentID     int64
	ID              int64
	Name            string
	ApiType         string
	NetworkExposure InventoryNetworkExposure
}

func (q *Queries) ListAPIsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListAPIsByComponentIDsRow, error) {
	rows, err := q.db.Query(ctx, listAPIsByComponentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIsByComponentIDsRow{}
	for rows.Next() {
		var i ListAPIsByComponentIDsRow
		if err := rows.Scan(
			&i.ComponentID,
			&i.ID,
			&i.Name,
			&i.ApiType,
			&i.NetworkExposure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
