// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"
)

const batchCreateClients = `-- name: BatchCreateClients :many
WITH input AS (
    SELECT client_names.client_name, communication_types.communication_type, capabilities.capabilities, secure_connections.secure_connection, client_names.ordinality
    FROM unnest($2::TEXT[]) WITH ORDINALITY AS client_names(client_name, ordinality)
    JOIN unnest($3::TEXT[]) WITH ORDINALITY AS communication_types(communication_type, ordinality)
        USING (ordinality)
    JOIN unnest($4::TEXT[]) WITH ORDINALITY AS capabilities(capabilities, ordinality)
        USING (ordinality)
    JOIN unnest($5::BOOLEAN[]) WITH ORDINALITY AS secure_connections(secure_connection, ordinality)
        USING (ordinality)
)
INSERT INTO inventory.component_clients (
    component_id,
    client_name,
    communication_type,
    capabilities,
    secure_connection
)
SELECT $1, client_name, communication_type, NULLIF(capabilities, ''), secure_connection
FROM input
ORDER BY ordinality
RETURNING id, component_id, client_name, communication_type, capabilities, secure_connection
`

type BatchCreateClientsParams struct {
	ComponentID        int64
	ClientNames        []string
	CommunicationTypes []string
	Capabilities       []string
	SecureConnections  []bool
}

func (q *Queries) BatchCreateClients(ctx context.Context, arg BatchCreateClientsParams) ([]InventoryComponentClient, error) {
	rows, err := q.db.Query(ctx, batchCreateClients,
		arg.ComponentID,
		arg.ClientNames,
		arg.CommunicationTypes,
		arg.Capabilities,
		arg.SecureConnections,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryComponentClient{}
	for rows.Next() {
		var i InventoryComponentClient
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.ClientName,
			&i.CommunicationType,
			&i.Capabilities,
			&i.SecureConnection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countClientsByComponentID = `-- name: CountClientsByComponentID :one
SELECT count(*)
FROM inventory.component_clients
WHERE component_id = $1
`

func (q *Queries) CountClientsByComponentID(ctx context.Context, componentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClientsByComponentID, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO inventory.component_clients (
    component_id,
    client_name,
    communication_type,
    capabilities,
    secure_connection
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, component_id, client_name, communication_type, capabilities, secure_connection
`

type CreateClientParams struct {
	ComponentID       int64
	ClientName        string
	CommunicationType string
	Capabilities      *string
	SecureConnection  bool
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (InventoryComponentClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ComponentID,
		arg.ClientName,
		arg.CommunicationType,
		arg.Capabilities,
		arg.SecureConnection,
	)
	var i InventoryComponentClient
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.ClientName,
		&i.CommunicationType,
		&i.Capabilities,
		&i.SecureConnection,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :one
DELETE FROM inventory.component_clients
WHERE id = $1
  AND component_id = $2
RETURNING id
`

type DeleteClientParams struct {
	ClientID    int64
	ComponentID int64
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteClient, arg.ClientID, arg.ComponentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listClientsByComponentIDs = `-- name: ListClientsByComponentIDs :many
SELECT
    component_clients.component_id,
    component_clients.id,
    component_clients.client_name,
    component_clients.communication_type,
    component_clients.capabilities,
    component_clients.secure_connection
FROM inventory.component_clients
WHERE component_clients.component_id = ANY($1::BIGINT[])
ORDER BY component_clients.component_id, component_clients.id
`

type ListClientsByComponentIDsRow struct {
	ComponentID       int64
	ID                int64
	ClientName        string
	CommunicationType string
	Capabilities      *string
	SecureConnection  bool
}

func (q *Queries) ListClientsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListClientsByComponentIDsRow, error) {
	rows, err := q.db.Query(ctx, listClientsByComponentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsByComponentIDsRow{}
	for rows.Next() {
		var i ListClientsByComponentIDsRow
		if err := rows.Scan(
			&i.ComponentID,
			&i.ID,
			&i.ClientName,
			&i.CommunicationType,
			&i.Capabilities,
			&i.SecureConnection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE inventory.component_clients
SET client_name = $1,
    communication_type = $2,
    capabilities = $3,
    secure_connection = $4
WHERE id = $5
  AND component_id = $6
RETURNING id, component_id, client_name, communication_type, capabilities, secure_connection
`

type UpdateClientParams struct {
	ClientName        string
	CommunicationType string
	Capabilities      *string
	SecureConnection  bool
	ClientID          int64
	ComponentID       int64
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (InventoryComponentClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ClientName,
		arg.CommunicationType,
		arg.Capabilities,
		arg.SecureConnection,
		arg.ClientID,
		arg.ComponentID,
	)
	var i InventoryComponentClient
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.ClientName,
		&i.CommunicationType,
		&i.Capabilities,
		&i.SecureConnection,
	)
	return i, err
}
