// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlc

import (
	"context"
)

const batchCreateClients = `-- name: BatchCreateClients :many
WITH input AS (
    SELECT client_names.client_name, roles.role, communication_types.communication_type, descriptions.description, client_names.ordinality
    FROM unnest($2::TEXT[]) WITH ORDINALITY AS client_names(client_name, ordinality)
    JOIN unnest($3::TEXT[]) WITH ORDINALITY AS roles(role, ordinality)
        USING (ordinality)
    JOIN unnest($4::TEXT[]) WITH ORDINALITY AS communication_types(communication_type, ordinality)
        USING (ordinality)
    JOIN unnest($5::TEXT[]) WITH ORDINALITY AS descriptions(description, ordinality)
        USING (ordinality)
)
INSERT INTO inventory.component_clients (
    component_id,
    client_name,
    role,
    communication_type,
    description
)
SELECT $1, client_name, role, communication_type, description
FROM input
ORDER BY ordinality
RETURNING id, component_id, client_name, role, communication_type, description, api_id
`

type BatchCreateClientsParams struct {
	ComponentID        int64
	ClientNames        []string
	Roles              []string
	CommunicationTypes []string
	Descriptions       []string
}

func (q *Queries) BatchCreateClients(ctx context.Context, arg BatchCreateClientsParams) ([]InventoryComponentClient, error) {
	rows, err := q.db.Query(ctx, batchCreateClients,
		arg.ComponentID,
		arg.ClientNames,
		arg.Roles,
		arg.CommunicationTypes,
		arg.Descriptions,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryComponentClient{}
	for rows.Next() {
		var i InventoryComponentClient
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.ClientName,
			&i.Role,
			&i.CommunicationType,
			&i.Description,
			&i.ApiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindClientAPI = `-- name: BindClientAPI :one
UPDATE inventory.component_clients
SET api_id = $1
WHERE id = $2
  AND api_id IS NULL
RETURNING id, component_id, client_name, role, communication_type, description, api_id
`

type BindClientAPIParams struct {
	ApiID    *int64
	ClientID int64
}

func (q *Queries) BindClientAPI(ctx context.Context, arg BindClientAPIParams) (InventoryComponentClient, error) {
	row := q.db.QueryRow(ctx, bindClientAPI, arg.ApiID, arg.ClientID)
	var i InventoryComponentClient
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.ClientName,
		&i.Role,
		&i.CommunicationType,
		&i.Description,
		&i.ApiID,
	)
	return i, err
}

const countClientsByComponentID = `-- name: CountClientsByComponentID :one
SELECT count(*)
FROM inventory.component_clients
WHERE component_id = $1
`

func (q *Queries) CountClientsByComponentID(ctx context.Context, componentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClientsByComponentID, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO inventory.component_clients (
    component_id,
    client_name,
    role,
    communication_type,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, component_id, client_name, role, communication_type, description, api_id
`

type CreateClientParams struct {
	ComponentID       int64
	ClientName        string
	Role              string
	CommunicationType string
	Description       *string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (InventoryComponentClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ComponentID,
		arg.ClientName,
		arg.Role,
		arg.CommunicationType,
		arg.Description,
	)
	var i InventoryComponentClient
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.ClientName,
		&i.Role,
		&i.CommunicationType,
		&i.Description,
		&i.ApiID,
	)
	return i, err
}

const getClientForAPIUpdate = `-- name: GetClientForAPIUpdate :one
SELECT
    source_client.id AS client_id,
    source_component.id AS component_id,
    source_component.product_id,
    source_client.api_id
FROM inventory.component_clients AS source_client
JOIN inventory.components AS source_component
    ON source_component.id = source_client.component_id
WHERE source_client.id = $1
  AND source_component.id = $2
FOR UPDATE OF source_client
FOR SHARE OF source_component
`

type GetClientForAPIUpdateParams struct {
	ClientID    int64
	ComponentID int64
}

type GetClientForAPIUpdateRow struct {
	ClientID    int64
	ComponentID int64
	ProductID   int64
	ApiID       *int64
}

func (q *Queries) GetClientForAPIUpdate(ctx context.Context, arg GetClientForAPIUpdateParams) (GetClientForAPIUpdateRow, error) {
	row := q.db.QueryRow(ctx, getClientForAPIUpdate, arg.ClientID, arg.ComponentID)
	var i GetClientForAPIUpdateRow
	err := row.Scan(
		&i.ClientID,
		&i.ComponentID,
		&i.ProductID,
		&i.ApiID,
	)
	return i, err
}

const getTargetAPIForShare = `-- name: GetTargetAPIForShare :one
SELECT
    target_api.id AS api_id,
    target_component.id AS component_id,
    target_component.product_id
FROM inventory.apis AS target_api
JOIN inventory.components AS target_component
    ON target_component.id = target_api.component_id
WHERE target_api.id = $1
FOR SHARE OF target_api, target_component
`

type GetTargetAPIForShareRow struct {
	ApiID       int64
	ComponentID int64
	ProductID   int64
}

func (q *Queries) GetTargetAPIForShare(ctx context.Context, apiID int64) (GetTargetAPIForShareRow, error) {
	row := q.db.QueryRow(ctx, getTargetAPIForShare, apiID)
	var i GetTargetAPIForShareRow
	err := row.Scan(&i.ApiID, &i.ComponentID, &i.ProductID)
	return i, err
}

const listClientsByComponentIDs = `-- name: ListClientsByComponentIDs :many
SELECT
    component_clients.component_id,
    component_clients.id,
    component_clients.client_name,
    component_clients.role,
    component_clients.communication_type,
    component_clients.description,
    component_clients.api_id
FROM inventory.component_clients
WHERE component_clients.component_id = ANY($1::BIGINT[])
ORDER BY component_clients.component_id, component_clients.id
`

type ListClientsByComponentIDsRow struct {
	ComponentID       int64
	ID                int64
	ClientName        string
	Role              string
	CommunicationType string
	Description       *string
	ApiID             *int64
}

func (q *Queries) ListClientsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListClientsByComponentIDsRow, error) {
	rows, err := q.db.Query(ctx, listClientsByComponentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsByComponentIDsRow{}
	for rows.Next() {
		var i ListClientsByComponentIDsRow
		if err := rows.Scan(
			&i.ComponentID,
			&i.ID,
			&i.ClientName,
			&i.Role,
			&i.CommunicationType,
			&i.Description,
			&i.ApiID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
