// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package sqlc

import (
	"context"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO inventory.components (
    product_id,
    name,
    description,
    component_type,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, product_id, name, description, component_type, details
`

type CreateComponentParams struct {
	ProductID     int64
	Name          string
	Description   *string
	ComponentType InventoryComponentType
	Details       []byte
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (InventoryComponent, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.ComponentType,
		arg.Details,
	)
	var i InventoryComponent
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.ComponentType,
		&i.Details,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :one
DELETE FROM inventory.components
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteComponent, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT
    id,
    product_id,
    name,
    description,
    component_type,
    details
FROM inventory.components
WHERE id = $1
`

func (q *Queries) GetComponentByID(ctx context.Context, id int64) (InventoryComponent, error) {
	row := q.db.QueryRow(ctx, getComponentByID, id)
	var i InventoryComponent
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.ComponentType,
		&i.Details,
	)
	return i, err
}

const listComponentsByProductID = `-- name: ListComponentsByProductID :many
WITH paged_components AS (
    SELECT
        id,
        product_id,
        name,
        description,
        component_type,
        details
    FROM inventory.components
    WHERE product_id = $1
    ORDER BY id
    LIMIT $3
    OFFSET $2
)
SELECT id, product_id, name, description, component_type, details
FROM paged_components
ORDER BY id
`

type ListComponentsByProductIDParams struct {
	ProductID int64
	Offset    int32
	Limit     int32
}

type ListComponentsByProductIDRow struct {
	ID            int64
	ProductID     int64
	Name          string
	Description   *string
	ComponentType InventoryComponentType
	Details       []byte
}

func (q *Queries) ListComponentsByProductID(ctx context.Context, arg ListComponentsByProductIDParams) ([]ListComponentsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listComponentsByProductID, arg.ProductID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComponentsByProductIDRow{}
	for rows.Next() {
		var i ListComponentsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.ComponentType,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockComponentForUpdate = `-- name: LockComponentForUpdate :one
SELECT id
FROM inventory.components
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockComponentForUpdate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockComponentForUpdate, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
