// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package sqlc

import (
	"context"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO inventory.client_integrations (client_id, api_id, action, description)
VALUES ($1, $2, $3, $4)
RETURNING id, client_id, api_id, action, description
`

type CreateIntegrationParams struct {
	ClientID    int64
	ApiID       int64
	Action      string
	Description *string
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (InventoryClientIntegration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.ClientID,
		arg.ApiID,
		arg.Action,
		arg.Description,
	)
	var i InventoryClientIntegration
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApiID,
		&i.Action,
		&i.Description,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :one
DELETE FROM inventory.client_integrations
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteIntegration(ctx context.Context, integrationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteIntegration, integrationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getIntegrationAPIForShare = `-- name: GetIntegrationAPIForShare :one
SELECT
    api.id,
    component.id AS component_id,
    component.product_id
FROM inventory.apis AS api
JOIN inventory.components AS component ON component.id = api.component_id
WHERE api.id = $1
FOR SHARE OF api, component
`

type GetIntegrationAPIForShareRow struct {
	ID          int64
	ComponentID int64
	ProductID   int64
}

func (q *Queries) GetIntegrationAPIForShare(ctx context.Context, apiID int64) (GetIntegrationAPIForShareRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationAPIForShare, apiID)
	var i GetIntegrationAPIForShareRow
	err := row.Scan(&i.ID, &i.ComponentID, &i.ProductID)
	return i, err
}

const getIntegrationClientForShare = `-- name: GetIntegrationClientForShare :one
SELECT
    client.id,
    client.client_name,
    client.communication_type,
    client.capabilities,
    client.secure_connection,
    component.id AS component_id,
    component.product_id
FROM inventory.component_clients AS client
JOIN inventory.components AS component ON component.id = client.component_id
WHERE client.id = $1
FOR SHARE OF client, component
`

type GetIntegrationClientForShareRow struct {
	ID                int64
	ClientName        string
	CommunicationType string
	Capabilities      *string
	SecureConnection  bool
	ComponentID       int64
	ProductID         int64
}

func (q *Queries) GetIntegrationClientForShare(ctx context.Context, clientID int64) (GetIntegrationClientForShareRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationClientForShare, clientID)
	var i GetIntegrationClientForShareRow
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.CommunicationType,
		&i.Capabilities,
		&i.SecureConnection,
		&i.ComponentID,
		&i.ProductID,
	)
	return i, err
}

const getIntegrationForUpdate = `-- name: GetIntegrationForUpdate :one
SELECT id, client_id, api_id, action, description
FROM inventory.client_integrations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetIntegrationForUpdate(ctx context.Context, integrationID int64) (InventoryClientIntegration, error) {
	row := q.db.QueryRow(ctx, getIntegrationForUpdate, integrationID)
	var i InventoryClientIntegration
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApiID,
		&i.Action,
		&i.Description,
	)
	return i, err
}

const listIntegrationsByClientIDs = `-- name: ListIntegrationsByClientIDs :many
SELECT id, client_id, api_id, action, description
FROM inventory.client_integrations
WHERE client_id = ANY($1::BIGINT[])
ORDER BY client_id, id
`

func (q *Queries) ListIntegrationsByClientIDs(ctx context.Context, clientIds []int64) ([]InventoryClientIntegration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByClientIDs, clientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryClientIntegration{}
	for rows.Next() {
		var i InventoryClientIntegration
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ApiID,
			&i.Action,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationDescription = `-- name: UpdateIntegrationDescription :one
UPDATE inventory.client_integrations
SET description = $1
WHERE id = $2
RETURNING id, client_id, api_id, action, description
`

type UpdateIntegrationDescriptionParams struct {
	Description   *string
	IntegrationID int64
}

func (q *Queries) UpdateIntegrationDescription(ctx context.Context, arg UpdateIntegrationDescriptionParams) (InventoryClientIntegration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationDescription, arg.Description, arg.IntegrationID)
	var i InventoryClientIntegration
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ApiID,
		&i.Action,
		&i.Description,
	)
	return i, err
}
