// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO inventory.products (
    workspace_id,
    product_code,
    owning_team_id,
    name,
    criticality,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, workspace_id, product_code, owning_team_id, name, criticality, description
`

type CreateProductParams struct {
	WorkspaceID  int64
	ProductCode  string
	OwningTeamID *int64
	Name         string
	Criticality  InventoryProductCriticality
	Description  *string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (InventoryProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.WorkspaceID,
		arg.ProductCode,
		arg.OwningTeamID,
		arg.Name,
		arg.Criticality,
		arg.Description,
	)
	var i InventoryProduct
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductCode,
		&i.OwningTeamID,
		&i.Name,
		&i.Criticality,
		&i.Description,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM inventory.products
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, workspace_id, product_code, owning_team_id, name, criticality, description
FROM inventory.products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (InventoryProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i InventoryProduct
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProductCode,
		&i.OwningTeamID,
		&i.Name,
		&i.Criticality,
		&i.Description,
	)
	return i, err
}

const listProductsByWorkspaceID = `-- name: ListProductsByWorkspaceID :many
SELECT id, workspace_id, product_code, owning_team_id, name, criticality, description
FROM inventory.products
WHERE workspace_id = $1
ORDER BY id
LIMIT $3
OFFSET $2
`

type ListProductsByWorkspaceIDParams struct {
	WorkspaceID int64
	Offset      int32
	Limit       int32
}

func (q *Queries) ListProductsByWorkspaceID(ctx context.Context, arg ListProductsByWorkspaceIDParams) ([]InventoryProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByWorkspaceID, arg.WorkspaceID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryProduct{}
	for rows.Next() {
		var i InventoryProduct
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProductCode,
			&i.OwningTeamID,
			&i.Name,
			&i.Criticality,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
