// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	BatchCreateAPIs(ctx context.Context, arg BatchCreateAPIsParams) ([]InventoryApi, error)
	BatchCreateClients(ctx context.Context, arg BatchCreateClientsParams) ([]InventoryComponentClient, error)
	BindClientAPI(ctx context.Context, arg BindClientAPIParams) (InventoryComponentClient, error)
	CountAPIsByComponentID(ctx context.Context, componentID int64) (int64, error)
	CountClientsByComponentID(ctx context.Context, componentID int64) (int64, error)
	CreateAPI(ctx context.Context, arg CreateAPIParams) (InventoryApi, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (InventoryComponentClient, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (InventoryComponent, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (InventoryProduct, error)
	CreateWorkspace(ctx context.Context, name string) (InventoryWorkspace, error)
	DeleteComponent(ctx context.Context, id int64) (int64, error)
	DeleteProduct(ctx context.Context, id int64) (int64, error)
	DeleteWorkspace(ctx context.Context, id int64) (int64, error)
	GetClientForAPIUpdate(ctx context.Context, arg GetClientForAPIUpdateParams) (GetClientForAPIUpdateRow, error)
	GetComponentByID(ctx context.Context, id int64) (InventoryComponent, error)
	GetProductByID(ctx context.Context, id int64) (InventoryProduct, error)
	GetTargetAPIForShare(ctx context.Context, apiID int64) (GetTargetAPIForShareRow, error)
	GetWorkspaceByID(ctx context.Context, id int64) (InventoryWorkspace, error)
	ListAPIsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListAPIsByComponentIDsRow, error)
	ListClientsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListClientsByComponentIDsRow, error)
	ListComponentsByProductID(ctx context.Context, arg ListComponentsByProductIDParams) ([]ListComponentsByProductIDRow, error)
	ListProductsByWorkspaceID(ctx context.Context, arg ListProductsByWorkspaceIDParams) ([]InventoryProduct, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]InventoryWorkspace, error)
	LockComponentForUpdate(ctx context.Context, id int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
