// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	BatchCreateAPIs(ctx context.Context, arg BatchCreateAPIsParams) ([]InventoryApi, error)
	BatchCreateClients(ctx context.Context, arg BatchCreateClientsParams) ([]InventoryComponentClient, error)
	CountAPIsByComponentID(ctx context.Context, componentID int64) (int64, error)
	CountClientsByComponentID(ctx context.Context, componentID int64) (int64, error)
	CreateAPI(ctx context.Context, arg CreateAPIParams) (InventoryApi, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (InventoryComponentClient, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (InventoryComponent, error)
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (InventoryClientIntegration, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (InventoryProduct, error)
	CreateWorkspace(ctx context.Context, name string) (InventoryWorkspace, error)
	DeleteAPI(ctx context.Context, arg DeleteAPIParams) (int64, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) (int64, error)
	DeleteComponent(ctx context.Context, id int64) (int64, error)
	DeleteIntegration(ctx context.Context, integrationID int64) (int64, error)
	DeleteProduct(ctx context.Context, id int64) (int64, error)
	DeleteWorkspace(ctx context.Context, id int64) (int64, error)
	GetComponentByID(ctx context.Context, id int64) (InventoryComponent, error)
	GetIntegrationAPIForShare(ctx context.Context, apiID int64) (GetIntegrationAPIForShareRow, error)
	GetIntegrationClientForShare(ctx context.Context, clientID int64) (GetIntegrationClientForShareRow, error)
	GetIntegrationForUpdate(ctx context.Context, integrationID int64) (InventoryClientIntegration, error)
	GetProductByID(ctx context.Context, id int64) (InventoryProduct, error)
	GetWorkspaceByID(ctx context.Context, id int64) (InventoryWorkspace, error)
	ListAPIsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListAPIsByComponentIDsRow, error)
	ListClientsByComponentIDs(ctx context.Context, dollar_1 []int64) ([]ListClientsByComponentIDsRow, error)
	ListComponentsByProductID(ctx context.Context, arg ListComponentsByProductIDParams) ([]ListComponentsByProductIDRow, error)
	ListIntegrationsByClientIDs(ctx context.Context, clientIds []int64) ([]InventoryClientIntegration, error)
	ListProductsByWorkspaceID(ctx context.Context, arg ListProductsByWorkspaceIDParams) ([]InventoryProduct, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]InventoryWorkspace, error)
	LockComponentForUpdate(ctx context.Context, id int64) (int64, error)
	UpdateAPI(ctx context.Context, arg UpdateAPIParams) (InventoryApi, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (InventoryComponentClient, error)
	UpdateIntegrationDescription(ctx context.Context, arg UpdateIntegrationDescriptionParams) (InventoryClientIntegration, error)
}

var _ Querier = (*Queries)(nil)
